/**
 * Result synthesizer: combines tool outputs into a coherent report.
 * Uses Claude API when available, falls back to template-based synthesis.
 */
import { config } from "../shared/config.js";

interface Task {
  title: string;
  description: string;
}

interface ToolResult {
  toolId: string;
  cost: number;
  data: unknown;
}

function templateSynthesize(task: Task, results: ToolResult[]): string {
  const sections: string[] = [];

  sections.push(`# ${task.title}\n`);
  sections.push(`> Task: ${task.description}\n`);

  for (const result of results) {
    const data = result.data as Record<string, unknown>;

    switch (result.toolId) {
      case "stock-data":
        sections.push(`## Stock Data`);
        sections.push(`- **Symbol:** ${data.symbol}`);
        sections.push(`- **Price:** $${data.price}`);
        sections.push(`- **Change:** ${data.change} (${data.changePercent})`);
        sections.push(`- **Volume:** ${data.volume}`);
        sections.push(`- **Day Range:** $${data.low} - $${data.high}`);
        sections.push(`- *Data source: ${data.source || "AgentEconomy"}*\n`);
        break;

      case "web-search": {
        const searchResults = (data.results || []) as Array<{
          title: string;
          snippet: string;
          url: string;
        }>;
        sections.push(`## Research Findings`);
        sections.push(`Search query: "${data.query}"\n`);
        for (const r of searchResults) {
          sections.push(`### ${r.title}`);
          sections.push(`${r.snippet}\n`);
        }
        break;
      }

      case "chart-gen":
        sections.push(`## Visualization`);
        sections.push("```");
        sections.push(data.textRepresentation as string);
        sections.push("```\n");
        break;

      case "translate":
        sections.push(`## Translation`);
        sections.push(`- **Original (${data.from}):** ${data.originalText}`);
        sections.push(`- **Translated (${data.to}):** ${data.translatedText}`);
        sections.push(
          `- **Confidence:** ${((data.confidence as number) * 100).toFixed(
            0
          )}%\n`
        );
        break;

      case "news": {
        const articles = (data.articles || []) as Array<{
          title: string;
          summary: string;
        }>;
        sections.push(`## Latest News: ${data.topic}`);
        for (const a of articles) {
          sections.push(`- **${a.title}**: ${a.summary}`);
        }
        sections.push("");
        break;
      }

      default:
        sections.push(`## ${result.toolId} Results`);
        sections.push("```json");
        sections.push(JSON.stringify(data, null, 2));
        sections.push("```\n");
    }
  }

  // Cost summary
  const totalCost = results.reduce((sum, r) => sum + r.cost, 0);
  sections.push(`---`);
  sections.push(`## Cost Summary`);
  for (const r of results) {
    sections.push(`- ${r.toolId}: $${r.cost.toFixed(2)}`);
  }
  sections.push(`- **Total tools cost:** $${totalCost.toFixed(2)}`);
  sections.push(`\n*Report generated by AgentEconomy AI Agent*`);

  return sections.join("\n");
}

async function llmSynthesize(
  task: Task,
  results: ToolResult[]
): Promise<string | null> {
  const apiKey = config.openrouterApiKey || config.anthropicApiKey;
  if (!apiKey) return null;

  const useOpenRouter = !!config.openrouterApiKey;
  const prompt = `You are an AI agent that just completed a task by calling paid tools. Synthesize the results into a clear, professional markdown report.

Task: ${task.title}
Description: ${task.description}

Tool results:
${results
  .map(
    (r) =>
      `### ${r.toolId} ($${r.cost.toFixed(2)})\n${JSON.stringify(
        r.data,
        null,
        2
      )}`
  )
  .join("\n\n")}

Write a comprehensive report that:
1. Has a clear title and executive summary
2. Presents key findings from each tool
3. Provides analysis and insights
4. Ends with a cost summary showing each tool's cost and total

Format as clean markdown. Be concise but thorough.`;

  try {
    if (useOpenRouter) {
      const response = await fetch(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: "anthropic/claude-sonnet-4",
            max_tokens: 2048,
            messages: [{ role: "user", content: prompt }],
          }),
        }
      );
      if (!response.ok) {
        console.log(`[Synthesizer] OpenRouter error: ${response.status}`);
        return null;
      }
      const data = (await response.json()) as {
        choices: Array<{ message: { content: string } }>;
      };
      return data.choices?.[0]?.message?.content || null;
    }

    // Anthropic direct
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 2048,
        messages: [{ role: "user", content: prompt }],
      }),
    });
    if (!response.ok) return null;
    const data = (await response.json()) as {
      content: Array<{ type: string; text: string }>;
    };
    return data.content.find((c) => c.type === "text")?.text || null;
  } catch {
    return null;
  }
}

export async function synthesizeResult(
  task: Task,
  results: ToolResult[]
): Promise<string> {
  const llmResult = await llmSynthesize(task, results);
  if (llmResult) {
    console.log("[Synthesizer] Using LLM synthesis");
    return llmResult;
  }

  console.log("[Synthesizer] Using template-based synthesis");
  return templateSynthesize(task, results);
}
